name: WubbaLubba

settings:
  MARKETING_VERSION: "0.1.0"
  SWIFT_VERSION: 5.7
  VERSIONING_SYSTEM: "apple-generic"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  xcodeVersion: "14.3"
  createIntermediateGroups: true
  developmentLanguage: "es-US"
  bundleIdPrefix: com.rickmorty
  deploymentTarget:
    iOS: 15.0
    macOS: 12.0

configs:
  Debug: debug
  Release: release

targets:
  NetworkClient:
    templates:
      - iOSFramework
  NetworkClientTests:
    templates:
      - iOSFrameworkTests
    dependencies:
      - target: NetworkClient

  RickMortyDomain:
    templates:
      - iOSFramework
    dependencies:
      - target: NetworkClient
  RickMortyDomainTests:
    templates:
      - iOSFrameworkTests
    dependencies:
      - target: RickMortyDomain

  RickMortyUI:
    templates:
      - iOSFramework
    dependencies:
      - target: RickMortyDomain
  RickMortyUITests:
    templates:
      - iOSFrameworkTests
    dependencies:
      - target: RickMortyUI
  
  WubbaLubba:
    templates:
      - iOSApp
    dependencies:
      - target: NetworkClient
      - target: RickMortyDomain
      - target: RickMortyUI

  WubbaLubbaTests:
    templates:
      - iOSAppTests
    dependencies:
      - target: WubbaLubba

  WubbaLubbaUITests:
    templates:
      - iOSAppUITests
    dependencies:
      - target: WubbaLubba

schemes:
  WubbaLubba:
    build:
      targets:
        WubbaLubba: [run, test, archive]
    archive:
      config: Release
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - WubbaLubba
      targets:
        - name: WubbaLubbaTests
          randomExecutionOrder: true
        - name: WubbaLubbaUITests
          randomExecutionOrder: true

  RickMortyUI:
    build:
      targets:
        RickMortyUI: [run, test]
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - RickMortyUI
      targets:
        - name: RickMortyUITests
          randomExecutionOrder: true

  RickMortyDomain:
    build:
      targets:
        RickMortyDomain: [run, test]
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - RickMortyDomain
      targets:
        - name: RickMortyDomainTests
          randomExecutionOrder: true

  NetworkClient:
    build:
      targets:
        NetworkClient: [run, test]
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - NetworkClient
      targets:
        - name: NetworkClientTests
          randomExecutionOrder: true

  CI-macOS:
    build:
      targets:
        RickMortyDomain: [run, test]
        NetworkClient: [run, test]
    run:
      config: Debug
    test: 
      config: Debug
      targets:
        - name: RickMortyDomainTests
          randomExecutionOrder: true
        - name: NetworkClientTests
          randomExecutionOrder: true

  CI-iOS:
    build:
      targets:
        RickMortyUI: [run, test]
        WubbaLubba: [run, test]
    run:
      config: Debug
    test: 
      config: Debug
      targets:
        - name: RickMortyUITests
          randomExecutionOrder: true
        - name: WubbaLubbaTests
          randomExecutionOrder: true
        - name: WubbaLubbaUITests
          randomExecutionOrder: true

targetTemplates:
  iOSFramework:
    platform: iOS
    type: framework
    sources:
      - path: ${target_name}
    info:
      path: ${target_name}/Info.plist

  iOSFrameworkTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: ${target_name}
      - path: XCTestCase
        createIntermediateGroups: false
        type: group
    info:
      path: ${target_name}/Info.plist
      
  iOSApp:
    platform: iOS
    type: application
    sources: 
      - path: ${target_name}
    settings:
      base:
        INFOPLIST_FILE: ${target_name}/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.rickmorty.WubbaLubba
      configs:
        Release:
          CODE_SIGN_IDENTITY: "{INSERT APPLE DISTRIBUTION}"
          PROVISIONING_PROFILE_SPECIFIER: "{INSET MATCH APP STORE}"
        Debug:
          CODE_SIGN_IDENTITY: "{INSERT APPLE DEVELOPER}"
          PROVISIONING_PROFILE_SPECIFIER: "{INSET MATCH DEVELOPMENT}"


  iOSAppTests:
    platform: iOS
    type: bundle.unit-test
    sources: 
      - path: ${target_name}
      - path: XCTestCase
        createIntermediateGroups: false
        type: group
    info:
      path: ${target_name}/Info.plist

  iOSAppUITests: 
    platform: iOS
    type: bundle.ui-testing
    sources: 
      - path: ${target_name}
    info:
      path: ${target_name}/Info.plist