name: WubbaLubba

settings:
  MARKETING_VERSION: "0.1.0"
  SWIFT_VERSION: 5.7
  VERSIONING_SYSTEM: "apple-generic"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  xcodeVersion: "14.3"
  createIntermediateGroups: true
  developmentLanguage: "es-US"
  bundlePrefix: com.RickMorty
  deploymentTarget:
    iOS: 15.0
    macOS: 12.0

configs:
  Debug: debug
  Release: release

targets:
  NetworkClient:
    templates:
      - iOSFramework
  NetworkClientTests:
    templates:
      - iOSFrameworkTests
    dependencies:
      - target: NetworkClient

  RickMortyDomain:
    templates:
      - iOSFramework
    dependencies:
      - target: NetworkClient
  RickMortyDomainTests:
    templates:
      - iOSFrameworkTests
    dependencies:
      - target: RickMortyDomain

  RickMortyUI:
    templates:
      - iOSFramework
    dependencies:
      - target: RickMortyDomain
  RickMortyUITests:
    templates:
      - iOSFrameworkTests
    dependencies:
      - target: RickMortyUI
  

targetTemplates:
  CrossPlatform:
    platform: iOS
    type: framework
    sources:
      - path: ${target_name}
    info:
      path: ${target_name}/Info.plist

  CrossPlatformTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: ${target_name}
      - path: XCTestCase
        createIntermediateGroups: false
        type: group
    info:
      path: ${target_name}/Info.plist

  iOSFramework:
    platform: iOS
    type: framework
    sources:
      - path: ${target_name}
    info:
      path: ${target_name}/Info.plist

  iOSFrameworkTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: ${target_name}
      - path: XCTestCase
        createIntermediateGroups: false
        type: group
    info:
      path: ${target_name}/Info.plist
      