# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Lane to run Scheme CI-macOS"
lane :ci_macOS do
  scan(
      clean: true,
      scheme: "CI-macOS",
      sdk: "macosx",
      destination: "platform=macOS"
  )
end

desc "Lane to run Scheme CI-iOS"
lane :ci_iOS do
  scan(
      clean: true,
      scheme: "CI-iOS",
      sdk: "iphonesimulator",
      destination: "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.4"
  )
end